// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  developSidebar: [{type: 'autogenerated', dirName: 'develop'}],
  buildSidebar: [{type: 'autogenerated', dirName: 'build'}],
};

module.exports = sidebars;
